/*NUMBER GUESSING GAME

The fun and easy project "Guess the Number" is a short Java project that allows the 
user to guess the number generated by the computer and involves the following steps:
1. The system generates a random number from a given range, say 1 to 100.
2. The user is prompted to enter their given number in a displayed dialogue box.
3. The computer then tells if the entered number matches the guesses number or it is 
higher/lower than the generated number.
4. The game continues under the user guessing the number.

You can also incorporate further details as:
Limiting the number of attempts.
Adding more rounds
Displaying score
Giving points based on the number of attempts.*/

package number_guessing;

import java.util.Random;
import java.util.Scanner;

public class NumberGuessingGame {
	private static final int Min_Range = 1;
	private static final int Max_Range = 100;
	private static final int Max_Attempts = 10;
	private static final int Max_Rounds = 3;
	private static int perfectScore = 0;
	static Scanner sc = new Scanner(System.in);
	
	public static void main(String[] args) {
		Random randomNumber = new Random();
		System.out.println("Welcome to Number Guessing Game");
		System.out.println("You have only Three rounds to play this game.");
		for(int round = 1; round <= Max_Rounds; round++) {
			System.out.println("Round "+ round +" of "+ Max_Rounds);
			int enterNumberToGuess = randomNumber.nextInt(Max_Range)+Min_Range;
			playGame(enterNumberToGuess);
		}
		endGame();
	}
	
	private static void playGame(int number) {
		int attempts = 0;
		boolean estimatedCorrectly = false;
		
		while(!estimatedCorrectly && attempts < Max_Attempts) {
			System.out.println("Guess a random number between 1 and 100");
			int guess = sc.nextInt();
			attempts++;
			
			if(guess < Min_Range || guess > Max_Range) {
				System.out.println("Invalid Number Entered. Please enter a number between 1 and 100");
			}else if(guess < number) {
				System.out.println("The entered number is less than the guessing number");
			}else if(guess > number) {
				System.out.println("The entered number is greater than the guessing number");
			}else {
				estimatedCorrectly = true;
				System.out.println("Excellent!! Finally you did it");
				int score = Max_Attempts - attempts;
				perfectScore += score;
				System.out.println("You takes "+attempts +" attempts to guess the number");
				System.out.println("Your score is : "+score);
			}
			if(attempts == Max_Attempts && !estimatedCorrectly) {
				System.out.println("You have done with all the attempts. The correct number is : "+number);
			}
		}
	}
	
	private static void endGame() {
		System.out.println("Thank You. Game Over! Your final score is : "+perfectScore);
	}
}
